export const FETCH_DATA_TODO = 'FETCH_DATA_TODO';
export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const FETCH_DELETE_TODO = 'FETCH_DELETE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const FETCH_UPDATE_TODO = 'FETCH_UPDATE_TODO';
export const ITEM_LOADED_TODO = 'ITEM_LOADED_TODO';
export const ERROR_TODO = 'ERROR_TODO';
