export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const FETCH_DATA_TODO = 'FETCH_DATA_TODO';
export const FETCH_DATA_SUCCESS_TODO = 'FETCH_DATA_SUCCESS_TODO';
export const ITEM_LOADED_TODO = 'ITEM_LOADED_TODO';
export const ITEM_ERROR_TODO = 'ITEM_ERROR_TODO';